library(plotly)
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Sierpinski Triangle 3D Visualization"),
  dashboardSidebar(
    # Adjust the number of iterations
    sliderInput("iterations", "Number of Iterations", min = 100, max = 50000, value = 5000),
    
    # Adjust colors
    selectInput("point_color", "Point Color", choices = c("red", "blue", "green", "black"), selected = "green"),
    
    # Adjust dot size
    sliderInput("dot_size", "Dot Size", min = 1, max = 10, value = 2),
    
    # Adjust dot transparency
    sliderInput("dot_transparency", "Dot Transparency", min = 0, max = 1, value = 0.4),
    
    # About section
    tags$hr(),
    h3("About"),
    p("Fractals are fascinating mathematical objects that exhibit self-similarity at different scales."),
    p("They have complex and intricate patterns that are generated through recursive algorithms."),
    p("In this app, you can explore the Sierpinski Triangle, which is a classic example of a fractal."),
    p("The Sierpinski Triangle is constructed by iteratively subdividing equilateral triangles."),
    p("Feel free to adjust the parameters on the left to customize your fractal visualization."),
    tags$hr(),
    
    # Help section
    h3("App Help"),
    p("This app allows you to interactively explore and visualize the Sierpinski Triangle in 3D."),
    p("Here's how to use this app:"),
    tags$ul(
      tags$li("Adjust the 'Number of Iterations' slider to control the complexity of the fractal."),
      tags$li("Select a 'Point Color' for the dots in the plot."),
      tags$li("Use the 'Dot Size' slider to change the size of the dots."),
      tags$li("The 'Dot Transparency' slider lets you control the opacity of the dots."),
      tags$li("As you adjust these parameters, the 3D Sierpinski Triangle plot will update in real-time."),
      tags$li("Explore and enjoy the intricate patterns generated by fractal mathematics!")
    )
  ),
  dashboardBody(
    plotlyOutput("sierpinski_plot", height = "1200px", width = "1200px")
  )
)
